Use flask's url_for because the toolkit one isn't working
Seems like it's using the pylons one? When called it's raising an exception:

GenerationException: url_for can only return a string, got unicode instead

which is odd.